### PR TITLE
PICT Parsing fixes - (Direct)BitsRect/Rgn 

### PR DESCRIPTION
**Pull request by assertivist**
Thanks to @tra we have better PICT parsing coverage. Embedded binary images were one of the last pieces of the puzzle we were missing I believe. I ported his fixes into the level converter and only a few fail to parse now (three out of... a lot).

### CODE REVIEW

**Comment by tra** [comment]
What are the 3 levels that fail to parse now?  I would be happy to look at them.  Especially if they have opcodes in the (Pack|Direct)Bits|(Rect|Regn) area then we probably have most of the code to do the parsing.

**Comment by assertivist** [comment]
1006_glas_glass.pict.svg
No support for opcode 0x502
20 20 00 a0 00 97 00 a0 00 8d 00 a1 00 96 00 0a 01 00 00 00 02 00 00 00 00 00 00 1a ff ff ff ff ff ff 00 0c 03 4a 03 d9 00 01 00 0a ff ff ff ff 04 d8 04 e0 00 09 00 00 00 00 00 00 00 00 00 31 00 b1 01 ca 00 c7 02 41 00 1a 00 00 00 00 00 00 00 0c fe 36 ff 4f 00 01 00 0a 00 00 00 00 00 16 00 77 00 23 00 00 00 03 00 04 00 28 00 09 00 00 0d 2f 2f 20 66 6f 72 20 66 6c 6f 6f 72 73 00 2a 0b 12 77 61 6c 6c 59 6f 6e 20 3d 20 66 6c 6f 6f 72 59 6f 6e 00 a0 00 97 00 a0 00 8c 00 0c 01 2d ff 77 00 01 00 0a fe c5 ff 62 03 9e 04 43 00 09 ff ff ff ff ff ff ff ff 00 23 00 00 00 a0 00 8c 00 23 00 00 00 a1 00 96 00 0a 01 00 00 00 02 00 00 00 00 00 00 1a 00 00 cc cc cc cc 00 31 00 37 00 dd 00 4f 01 60 00 1a 00 00 00 00 00 00 00 0c ff 23 ff c9 00 01 00 0a 00 00 00 00 00 18 00 83 00 23 00 00 00 03 00 03 00 28 00 0a 00 00 19 62 61 73 65 48 65 69 67 68 74 20 3d 20 68 65 61 64 52 6f 6f 6d 20 2a 20 31 20 20 20 20
Could not parse levels/gzr-geriatric-ward/svg/1006_glas_glass.pict.svg - Glasshouse because of unknown opcode

1000_dsrt_desert.pict.svg
No support for opcode 0x2020
20 00 00 28 00 8d 00 00 0d 77 65 61 70 6f 6e 59 20 3d 20 32 2e 31 00 00 10 64 65 66 61 75 6c 74 4c 69 76 65 73 20 3d 20 33 20 20 20 20 20 00 28 00 ae 00 00 11 6d 69 73 73 69 6c 65 50 6f 77 65 72 20 3d 20 31 30 00 2a 0b 19 6d 69 73 73 69 6c 65 41 63 63 65 6c 65 72 61 74 69 6f 6e 20 3d 20 30 2e 35 00 00 2a 0b 0a 73 74 61 72 74 59 20 3d 20 39 00 2a 0b 0b 2f 2f 20 67 72 65 6e 61 64 65 73 00 00 2a 0b 0f 67 72 65 6e 44 65 6c 61 79 20 3d 20 32 35 30 00 00 2a 0b 0b 6e 75 6d 47 72 65 6e 20 3d 20 36 00 00 2a 0b 0b 2f 2f 20 6d 69 73 73 69 6c 65 73 00 00 2a 0b 0f 6d 69 73 73 44 65 6c 61 79 20 3d 20 32 35 30 00 00 2a 0b 0b 6e 75 6d 4d 69 73 73 20 3d 20 34 00 00 a0 00 97 00 1a ff ff ff ff 00 00 00 0c 00 01 00 4f 00 01 00 0a ff ff ff ff 05 51 04 db 00 08 00 08 00 61 00 07 00 07 00 33 00 7b 01 0e 00 b4 00 22 01 06 00 42 00 00 00 a1 00 b6 00 04 00 01 00 01 00 1a aa aa 00 00 00 00 00 07 00 08 00 08 00 68
Could not parse levels/gzr-liver-spots/svg/1000_dsrt_desert.pict.svg - Desert Storm because of unknown opcode

I looked at this a little bit and couldn't figure out why the opcodes are weird. They seem to appear right after totally normal opcodes that we parse just fine.

**Comment by assertivist** [comment]
Also I should mention this is in the converter. They may work fine in Avara? I will check.

**Comment by assertivist** [comment]
These levels seemed to be functional in Avara, but I wouldn't be able to tell if there are objects missing because of a parsing failure.
```
INFO: LOADING LEVEL 1835627123 FROM gzr-over-the-hill
INFO: UNKNOWN OPCODE: 6400
INFO: Light from light table - idx: 0 i: 0.399994 a: 45.000000 b: 20.000000
INFO: Light from light table - idx: 1 i: 0.299988 a: 20.000000 b: 200.000000
INFO: Message: Loaded "Mirage" (gzr-over-the-hill).

INFO: LOADING LEVEL 1685287540 FROM gzr-liver-spots
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2000
INFO: UNKNOWN OPCODE: 1064
INFO: UNKNOWN OPCODE: 6566
INFO: UNKNOWN OPCODE: 6175
INFO: UNKNOWN OPCODE: 6c74
INFO: UNKNOWN OPCODE: 4c69
INFO: UNKNOWN OPCODE: 7665
INFO: UNKNOWN OPCODE: 7320
INFO: UNKNOWN OPCODE: 3d20
INFO: UNKNOWN OPCODE: 3320
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2020
INFO: Light from light table - idx: 0 i: 1.000000 a: 0.000000 b: 0.000000
INFO: Message: Loaded "Desert Storm" (gzr-liver-spots).

INFO: LOADING LEVEL 1735156083 FROM gzr-geriatric-ward
INFO: UNKNOWN OPCODE: 0502
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2000
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2020
INFO: UNKNOWN OPCODE: 2000
INFO: Light from light table - idx: 0 i: 0.399994 a: 45.000000 b: 20.000000
INFO: Light from light table - idx: 1 i: 0.299988 a: 20.000000 b: 200.000000
INFO: Message: Loaded "Glasshouse" (gzr-geriatric-ward).
```

**Comment by tra** [comment]
I wouldn't be surprised if some/all of those errors are due to me hand-editing some of the gzr levelsets.  I will restore them to the original and see what happens.  I've been meaning to do that anyways.

**Comment by tra** [comment]
[This pull request](https://github.com/avaraline/Avara/pull/78) replaces the gzr levels with their original versions.  Some didn't need to be replaced as they hadn't been updated.  I think that takes care of the levelsets in question.  Are there any others that you are aware of that don't parse?

**Pull request merged**
